name: kill_switch_flutter
description: A Flutter Package That Provides A Kill Switch Functionality For Apps Using Firebase Firestore
version: 0.0.3
homepage: https://github.com/muzzammil763/kill_switch
repository: https://github.com/muzzammil763/kill_switch
issue_tracker: https://github.com/muzzammil763/kill_switch/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: any
  firebase_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any